-- SQL script to create excel_formulas table and seed data
DROP TABLE IF EXISTS public.excel_formulas CASCADE;

CREATE TABLE public.excel_formulas (
  id SERIAL PRIMARY KEY,
  no INTEGER,
  nama_rumus TEXT NOT NULL,
  versi TEXT,
  syntax TEXT,
  penjelasan TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.excel_formulas ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Anyone can view formulas" ON public.excel_formulas
  FOR SELECT USING (true);

-- Insert rows
INSERT INTO public.excel_formulas (no, nama_rumus, versi, syntax, penjelasan) VALUES
  (1, 'ABS', '-', 'ABS(number)', 'Mengembalikan nilai absolut (positif) dari suatu angka'),
  (2, 'ACCRINT', '-', 'ACCRINT(issue, first_interest, settlement, rate, par, frequency, [basis], [calc_method])', 'Menghitung bunga yang bertambah untuk sekuritas yang membayar bunga berkala'),
  (3, 'ACCRINTM', '-', 'ACCRINTM(issue, settlement, rate, par, [basis])', 'Menghitung bunga yang bertambah untuk sekuritas yang membayar bunga pada saat jatuh tempo'),
  (4, 'ACOS', '-', 'ACOS(number)', 'Mengembalikan arkkosinus (kosinus invers) dari suatu angka dalam radian'),
  (5, 'ACOSH', '-', 'ACOSH(number)', 'Mengembalikan arkkosinus hiperbolik invers dari suatu angka'),
  (6, 'ACOT', 'Excel 2013+', 'ACOT(number)', 'Mengembalikan arkkotangen (kotangen invers) dari suatu angka dalam radian'),
  (7, 'ACOTH', 'Excel 2013+', 'ACOTH(number)', 'Mengembalikan arkkotangen hiperbolik invers dari suatu angka'),
  (8, 'AGGREGATE', '-', 'AGGREGATE(function_num, options, ref1, [ref2], ...)', 'Mengembalikan agregat dalam daftar atau database, dapat mengabaikan baris tersembunyi dan nilai error'),
  (9, 'ADDRESS', '-', 'ADDRESS(row_num, column_num, [abs_num], [a1], [sheet_text])', 'Membuat referensi sel sebagai teks berdasarkan nomor baris dan kolom'),
  (10, 'AMORDEGRC', '-', 'AMORDEGRC(cost, date_purchased, first_period, salvage, period, rate, [basis])', 'Mengembalikan depresiasi untuk setiap periode akuntansi menggunakan koefisien depresiasi'),
  (11, 'AMORLINC', '-', 'AMORLINC(cost, date_purchased, first_period, salvage, period, rate, [basis])', 'Mengembalikan depresiasi untuk setiap periode akuntansi secara linear'),
  (12, 'AND', '-', 'AND(logical1, [logical2], ...)', 'Mengembalikan TRUE jika semua argumen bernilai TRUE'),
  (13, 'ARABIC', 'Excel 2013+', 'ARABIC(text)', 'Mengkonversi angka Romawi menjadi angka Arab'),
  (14, 'AREAS', '-', 'AREAS(reference)', 'Mengembalikan jumlah area dalam suatu referensi'),
  (15, 'ARRAYTOTEXT', 'Excel 2021+', 'ARRAYTOTEXT(array, [format])', 'Mengembalikan array nilai teks dari rentang yang ditentukan'),
  (16, 'ASC', '-', 'ASC(text)', 'Mengubah karakter full-width (double-byte) menjadi half-width (single-byte) dalam teks'),
  (17, 'ASIN', '-', 'ASIN(number)', 'Mengembalikan arksinus (sinus invers) dari suatu angka dalam radian'),
  (18, 'ASINH', '-', 'ASINH(number)', 'Mengembalikan arksinus hiperbolik invers dari suatu angka'),
  (19, 'ATAN', '-', 'ATAN(number)', 'Mengembalikan arktangen (tangen invers) dari suatu angka dalam radian'),
  (20, 'ATAN2', '-', 'ATAN2(x_num, y_num)', 'Mengembalikan arktangen dari koordinat x dan y dalam radian'),
  (21, 'ATANH', '-', 'ATANH(number)', 'Mengembalikan arktangen hiperbolik invers dari suatu angka'),
  (22, 'AVEDEV', '-', 'AVEDEV(number1, [number2], ...)', 'Mengembalikan rata-rata deviasi absolut dari rata-rata sebuah kumpulan data'),
  (23, 'AVERAGE', '-', 'AVERAGE(number1, [number2], ...)', 'Mengembalikan rata-rata (mean aritmatika) dari argumen'),
  (24, 'AVERAGEA', '-', 'AVERAGEA(value1, [value2], ...)', 'Mengembalikan rata-rata dari argumen termasuk angka, teks, dan nilai logika'),
  (25, 'AVERAGEIF', '-', 'AVERAGEIF(range, criteria, [average_range])', 'Mengembalikan rata-rata dari sel yang memenuhi kriteria tertentu'),
  (26, 'AVERAGEIFS', '-', 'AVERAGEIFS(average_range, criteria_range1, criteria1, ...)', 'Mengembalikan rata-rata dari sel yang memenuhi beberapa kriteria'),
  (27, 'BAHTTEXT', '-', 'BAHTTEXT(number)', 'Mengkonversi angka menjadi teks dalam format mata uang Thai Baht'),
  (28, 'BASE', '-', 'BASE(number, radix, [min_length])', 'Mengkonversi angka menjadi representasi teks dengan basis bilangan yang diberikan'),
  (29, 'BESSELI', '-', 'BESSELI(x, n)', 'Mengembalikan fungsi Bessel termodifikasi In(x)'),
  (30, 'BESSELJ', '-', 'BESSELJ(x, n)', 'Mengembalikan fungsi Bessel Jn(x)'),
  (31, 'BESSELK', '-', 'BESSELK(x, n)', 'Mengembalikan fungsi Bessel termodifikasi Kn(x)'),
  (32, 'BESSELY', '-', 'BESSELY(x, n)', 'Mengembalikan fungsi Bessel Yn(x)'),
  (33, 'BETADIST', '-', 'BETADIST(x, alpha, beta, [A], [B])', 'Fungsi lama: Mengembalikan fungsi distribusi kumulatif beta (diganti BETA.DIST)'),
  (34, 'BETA.DIST', 'Excel 2010+', 'BETA.DIST(x, alpha, beta, cumulative, [A], [B])', 'Mengembalikan fungsi distribusi probabilitas beta'),
  (35, 'BETAINV', '-', 'BETAINV(probability, alpha, beta, [A], [B])', 'Fungsi lama: Mengembalikan invers dari fungsi distribusi kumulatif beta (diganti BETA.INV)'),
  (36, 'BETA.INV', 'Excel 2010+', 'BETA.INV(probability, alpha, beta, [A], [B])', 'Mengembalikan invers dari fungsi distribusi kumulatif beta'),
  (37, 'BIN2DEC', '-', 'BIN2DEC(number)', 'Mengkonversi bilangan biner menjadi desimal'),
  (38, 'BIN2HEX', '-', 'BIN2HEX(number, [places])', 'Mengkonversi bilangan biner menjadi heksadesimal'),
  (39, 'BIN2OCT', '-', 'BIN2OCT(number, [places])', 'Mengkonversi bilangan biner menjadi oktal'),
  (40, 'BINOMDIST', '-', 'BINOMDIST(number_s, trials, probability_s, cumulative)', 'Fungsi lama: Mengembalikan distribusi binomial individual (diganti BINOM.DIST)'),
  (41, 'BINOM.DIST', 'Excel 2010+', 'BINOM.DIST(number_s, trials, probability_s, cumulative)', 'Mengembalikan distribusi probabilitas binomial'),
  (42, 'BINOM.DIST.RANGE', 'Excel 2013+', 'BINOM.DIST.RANGE(trials, probability_s, number_s, [number_s2])', 'Mengembalikan probabilitas percobaan menggunakan distribusi binomial'),
  (43, 'BINOM.INV', 'Excel 2010+', 'BINOM.INV(trials, probability_s, alpha)', 'Mengembalikan nilai terkecil yang distribusi binomialnya kurang dari atau sama dengan nilai kriteria'),
  (44, 'BITAND', 'Excel 2013+', 'BITAND(number1, number2)', 'Mengembalikan hasil AND bitwise dari dua angka'),
  (45, 'BITLSHIFT', 'Excel 2013+', 'BITLSHIFT(number, shift_amount)', 'Mengembalikan angka yang digeser ke kiri sejumlah bit yang ditentukan'),
  (46, 'BITOR', 'Excel 2013+', 'BITOR(number1, number2)', 'Mengembalikan hasil OR bitwise dari dua angka'),
  (47, 'BITRSHIFT', 'Excel 2013+', 'BITRSHIFT(number, shift_amount)', 'Mengembalikan angka yang digeser ke kanan sejumlah bit yang ditentukan'),
  (48, 'BITXOR', 'Excel 2013+', 'BITXOR(number1, number2)', 'Mengembalikan hasil XOR bitwise dari dua angka'),
  (49, 'BYCOL', 'Excel 2024+', 'BYCOL(array, lambda)', 'Menerapkan fungsi LAMBDA ke setiap kolom dan mengembalikan array hasil'),
  (50, 'BYROW', 'Excel 2024+', 'BYROW(array, lambda)', 'Menerapkan fungsi LAMBDA ke setiap baris dan mengembalikan array hasil'),
  (51, 'CALL', '-', 'CALL(register_id, [argument1], ...)', 'Memanggil prosedur dalam DLL atau sumber daya kode'),
  (52, 'CEILING', '-', 'CEILING(number, significance)', 'Membulatkan angka ke atas ke kelipatan terdekat dari signifikansi'),
  (53, 'CEILING.MATH', 'Excel 2013+', 'CEILING.MATH(number, [significance], [mode])', 'Membulatkan angka ke atas ke bilangan bulat terdekat atau ke kelipatan signifikansi terdekat'),
  (54, 'CEILING.PRECISE', '-', 'CEILING.PRECISE(number, [significance])', 'Membulatkan angka ke atas ke bilangan bulat atau kelipatan signifikansi terdekat'),
  (55, 'CELL', '-', 'CELL(info_type, [reference])', 'Mengembalikan informasi tentang format, lokasi, atau konten sel'),
  (56, 'CHAR', '-', 'CHAR(number)', 'Mengembalikan karakter yang ditentukan oleh kode angka'),
  (57, 'CHIDIST', '-', 'CHIDIST(x, deg_freedom)', 'Fungsi lama: Mengembalikan probabilitas ekor kanan distribusi chi-kuadrat'),
  (58, 'CHIINV', '-', 'CHIINV(probability, deg_freedom)', 'Fungsi lama: Mengembalikan invers probabilitas ekor kanan distribusi chi-kuadrat'),
  (59, 'CHITEST', '-', 'CHITEST(actual_range, expected_range)', 'Fungsi lama: Mengembalikan uji independensi (diganti CHISQ.TEST)'),
  (60, 'CHISQ.DIST', 'Excel 2010+', 'CHISQ.DIST(x, deg_freedom, cumulative)', 'Mengembalikan distribusi chi-kuadrat'),
  (61, 'CHISQ.DIST.RT', 'Excel 2010+', 'CHISQ.DIST.RT(x, deg_freedom)', 'Mengembalikan probabilitas ekor kanan distribusi chi-kuadrat'),
  (62, 'CHISQ.INV', 'Excel 2010+', 'CHISQ.INV(probability, deg_freedom)', 'Mengembalikan invers distribusi chi-kuadrat ekor kiri'),
  (63, 'CHISQ.INV.RT', 'Excel 2010+', 'CHISQ.INV.RT(probability, deg_freedom)', 'Mengembalikan invers probabilitas ekor kanan distribusi chi-kuadrat'),
  (64, 'CHISQ.TEST', 'Excel 2010+', 'CHISQ.TEST(actual_range, expected_range)', 'Mengembalikan uji independensi menggunakan distribusi chi-kuadrat'),
  (65, 'CHOOSE', '-', 'CHOOSE(index_num, value1, [value2], ...)', 'Memilih nilai dari daftar nilai berdasarkan nomor indeks'),
  (66, 'CHOOSECOLS', 'Excel 2024+', 'CHOOSECOLS(array, col_num1, [col_num2], ...)', 'Mengembalikan kolom yang ditentukan dari array'),
  (67, 'CHOOSEROWS', 'Excel 2024+', 'CHOOSEROWS(array, row_num1, [row_num2], ...)', 'Mengembalikan baris yang ditentukan dari array'),
  (68, 'CLEAN', '-', 'CLEAN(text)', 'Menghapus semua karakter non-printable dari teks'),
  (69, 'CODE', '-', 'CODE(text)', 'Mengembalikan kode numerik untuk karakter pertama dalam string teks'),
  (70, 'COLUMN', '-', 'COLUMN([reference])', 'Mengembalikan nomor kolom dari suatu referensi'),
  (71, 'COLUMNS', '-', 'COLUMNS(array)', 'Mengembalikan jumlah kolom dalam suatu array atau referensi'),
  (72, 'COMBIN', '-', 'COMBIN(number, number_chosen)', 'Mengembalikan jumlah kombinasi untuk sejumlah item tertentu'),
  (73, 'COMBINA', 'Excel 2013+', 'COMBINA(number, number_chosen)', 'Mengembalikan jumlah kombinasi dengan pengulangan untuk sejumlah item'),
  (74, 'COMPLEX', '-', 'COMPLEX(real_num, i_num, [suffix])', 'Mengkonversi koefisien real dan imajiner menjadi bilangan kompleks'),
  (75, 'CONCAT', 'Excel 2019+', 'CONCAT(text1, [text2], ...)', 'Menggabungkan teks dari beberapa rentang atau string'),
  (76, 'CONCATENATE', '-', 'CONCATENATE(text1, [text2], ...)', 'Menggabungkan beberapa string teks menjadi satu string'),
  (77, 'CONFIDENCE', '-', 'CONFIDENCE(alpha, standard_dev, size)', 'Fungsi lama: Mengembalikan interval kepercayaan untuk rata-rata populasi (diganti CONFIDENCE.NORM)'),
  (78, 'CONFIDENCE.NORM', 'Excel 2010+', 'CONFIDENCE.NORM(alpha, standard_dev, size)', 'Mengembalikan interval kepercayaan untuk rata-rata populasi menggunakan distribusi normal'),
  (79, 'CONFIDENCE.T', 'Excel 2010+', 'CONFIDENCE.T(alpha, standard_dev, size)', 'Mengembalikan interval kepercayaan untuk rata-rata populasi menggunakan distribusi t-Student'),
  (80, 'CONVERT', '-', 'CONVERT(number, from_unit, to_unit)', 'Mengkonversi angka dari satu sistem pengukuran ke yang lain'),
  (81, 'CORREL', '-', 'CORREL(array1, array2)', 'Mengembalikan koefisien korelasi antara dua kumpulan data'),
  (82, 'COS', '-', 'COS(number)', 'Mengembalikan kosinus dari suatu sudut dalam radian'),
  (83, 'COSH', '-', 'COSH(number)', 'Mengembalikan kosinus hiperbolik dari suatu angka'),
  (84, 'COT', 'Excel 2013+', 'COT(number)', 'Mengembalikan kotangen dari suatu sudut dalam radian'),
  (85, 'COTH', 'Excel 2013+', 'COTH(number)', 'Mengembalikan kotangen hiperbolik dari suatu angka'),
  (86, 'COUNT', '-', 'COUNT(value1, [value2], ...)', 'Menghitung jumlah sel yang berisi angka dalam rentang'),
  (87, 'COUNTA', '-', 'COUNTA(value1, [value2], ...)', 'Menghitung jumlah sel yang tidak kosong dalam rentang'),
  (88, 'COUNTBLANK', '-', 'COUNTBLANK(range)', 'Menghitung jumlah sel kosong dalam rentang'),
  (89, 'COUNTIF', '-', 'COUNTIF(range, criteria)', 'Menghitung jumlah sel dalam rentang yang memenuhi satu kriteria'),
  (90, 'COUNTIFS', '-', 'COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)', 'Menghitung jumlah sel yang memenuhi beberapa kriteria'),
  (91, 'COUPDAYBS', '-', 'COUPDAYBS(settlement, maturity, frequency, [basis])', 'Mengembalikan jumlah hari dari awal periode kupon hingga tanggal penyelesaian'),
  (92, 'COUPDAYS', '-', 'COUPDAYS(settlement, maturity, frequency, [basis])', 'Mengembalikan jumlah hari dalam periode kupon yang berisi tanggal penyelesaian'),
  (93, 'COUPDAYSNC', '-', 'COUPDAYSNC(settlement, maturity, frequency, [basis])', 'Mengembalikan jumlah hari dari tanggal penyelesaian hingga tanggal kupon berikutnya'),
  (94, 'COUPNCD', '-', 'COUPNCD(settlement, maturity, frequency, [basis])', 'Mengembalikan tanggal kupon berikutnya setelah tanggal penyelesaian'),
  (95, 'COUPNUM', '-', 'COUPNUM(settlement, maturity, frequency, [basis])', 'Mengembalikan jumlah kupon yang jatuh tempo antara tanggal penyelesaian dan jatuh tempo'),
  (96, 'COUPPCD', '-', 'COUPPCD(settlement, maturity, frequency, [basis])', 'Mengembalikan tanggal kupon sebelumnya sebelum tanggal penyelesaian'),
  (97, 'COVAR', '-', 'COVAR(array1, array2)', 'Fungsi lama: Mengembalikan kovarians, rata-rata produk deviasi untuk setiap pasang titik data'),
  (98, 'COVARIANCE.P', 'Excel 2010+', 'COVARIANCE.P(array1, array2)', 'Mengembalikan kovarians populasi'),
  (99, 'COVARIANCE.S', 'Excel 2010+', 'COVARIANCE.S(array1, array2)', 'Mengembalikan kovarians sampel'),
  (100, 'CRITBINOM', '-', 'CRITBINOM(trials, probability_s, alpha)', 'Fungsi lama: Mengembalikan nilai terkecil untuk distribusi binomial kumulatif (diganti BINOM.INV)');

INSERT INTO public.excel_formulas (no, nama_rumus, versi, syntax, penjelasan) VALUES
  (101, 'CSC', 'Excel 2013+', 'CSC(number)', 'Mengembalikan kosekan dari suatu sudut dalam radian'),
  (102, 'CSCH', 'Excel 2013+', 'CSCH(number)', 'Mengembalikan kosekan hiperbolik dari suatu angka'),
  (103, 'CUBEKPIMEMBER', '-', 'CUBEKPIMEMBER(connection, kpi_name, kpi_property, [caption])', 'Mengembalikan properti KPI dan menampilkan nama KPI dalam sel'),
  (104, 'CUBEMEMBER', '-', 'CUBEMEMBER(connection, member_expression, [caption])', 'Mengembalikan anggota atau tuple dari hierarki cube'),
  (105, 'CUBEMEMBERPROPERTY', '-', 'CUBEMEMBERPROPERTY(connection, member_expression, property)', 'Mengembalikan nilai properti anggota dari cube'),
  (106, 'CUBERANKEDMEMBER', '-', 'CUBERANKEDMEMBER(connection, set_expression, rank, [caption])', 'Mengembalikan anggota ke-n dalam sebuah set'),
  (107, 'CUBESET', '-', 'CUBESET(connection, set_expression, [caption], [sort_order], [sort_by])', 'Mendefinisikan set anggota atau tuple yang dihitung dengan mengirim ekspresi set ke cube di server'),
  (108, 'CUBESETCOUNT', '-', 'CUBESETCOUNT(set)', 'Mengembalikan jumlah item dalam sebuah set'),
  (109, 'CUBEVALUE', '-', 'CUBEVALUE(connection, [member_expression1], ...)', 'Mengembalikan nilai agregat dari cube'),
  (110, 'CUMIPMT', '-', 'CUMIPMT(rate, nper, pv, start_period, end_period, type)', 'Mengembalikan bunga kumulatif yang dibayarkan antara dua periode'),
  (111, 'CUMPRINC', '-', 'CUMPRINC(rate, nper, pv, start_period, end_period, type)', 'Mengembalikan pokok kumulatif yang dibayarkan antara dua periode'),
  (112, 'DATE', '-', 'DATE(year, month, day)', 'Mengembalikan angka seri yang mewakili tanggal tertentu'),
  (113, 'DATEDIF', '-', 'DATEDIF(start_date, end_date, unit)', 'Menghitung selisih antara dua tanggal dalam unit yang ditentukan'),
  (114, 'DATEVALUE', '-', 'DATEVALUE(date_text)', 'Mengkonversi tanggal dalam bentuk teks menjadi angka seri'),
  (115, 'DAVERAGE', '-', 'DAVERAGE(database, field, criteria)', 'Mengembalikan rata-rata nilai dari kolom dalam daftar yang cocok dengan kondisi tertentu'),
  (116, 'DAY', '-', 'DAY(serial_number)', 'Mengembalikan hari dalam sebulan (1-31) dari suatu tanggal'),
  (117, 'DAYS', 'Excel 2013+', 'DAYS(end_date, start_date)', 'Mengembalikan jumlah hari antara dua tanggal'),
  (118, 'DAYS360', '-', 'DAYS360(start_date, end_date, [method])', 'Menghitung jumlah hari antara dua tanggal berdasarkan tahun 360 hari'),
  (119, 'DB', '-', 'DB(cost, salvage, life, period, [month])', 'Mengembalikan depresiasi aset menggunakan metode saldo menurun tetap'),
  (120, 'DBCS', 'Excel 2013+', 'DBCS(text)', 'Mengubah karakter half-width (single-byte) menjadi full-width (double-byte) dalam teks'),
  (121, 'DCOUNT', '-', 'DCOUNT(database, field, criteria)', 'Menghitung sel yang berisi angka dalam kolom database yang cocok dengan kondisi'),
  (122, 'DCOUNTA', '-', 'DCOUNTA(database, field, criteria)', 'Menghitung sel tidak kosong dalam kolom database yang cocok dengan kondisi'),
  (123, 'DDB', '-', 'DDB(cost, salvage, life, period, [factor])', 'Mengembalikan depresiasi aset menggunakan metode saldo menurun ganda'),
  (124, 'DEC2BIN', '-', 'DEC2BIN(number, [places])', 'Mengkonversi bilangan desimal menjadi biner'),
  (125, 'DEC2HEX', '-', 'DEC2HEX(number, [places])', 'Mengkonversi bilangan desimal menjadi heksadesimal'),
  (126, 'DEC2OCT', '-', 'DEC2OCT(number, [places])', 'Mengkonversi bilangan desimal menjadi oktal'),
  (127, 'DECIMAL', 'Excel 2013+', 'DECIMAL(text, radix)', 'Mengkonversi representasi teks dari angka dalam basis tertentu menjadi desimal'),
  (128, 'DEGREES', '-', 'DEGREES(angle)', 'Mengkonversi radian menjadi derajat'),
  (129, 'DELTA', '-', 'DELTA(number1, [number2])', 'Menguji apakah dua nilai sama, mengembalikan 1 jika sama, 0 jika tidak'),
  (130, 'DEVSQ', '-', 'DEVSQ(number1, [number2], ...)', 'Mengembalikan jumlah kuadrat deviasi dari rata-rata sampel'),
  (131, 'DGET', '-', 'DGET(database, field, criteria)', 'Mengekstrak satu nilai dari kolom database yang cocok dengan kondisi tertentu'),
  (132, 'DISC', '-', 'DISC(settlement, maturity, pr, redemption, [basis])', 'Mengembalikan tingkat diskonto untuk sekuritas'),
  (133, 'DMAX', '-', 'DMAX(database, field, criteria)', 'Mengembalikan nilai maksimum dari kolom database yang cocok dengan kondisi'),
  (134, 'DMIN', '-', 'DMIN(database, field, criteria)', 'Mengembalikan nilai minimum dari kolom database yang cocok dengan kondisi'),
  (135, 'DOLLAR', '-', 'DOLLAR(number, [decimals])', 'Mengkonversi angka menjadi teks dalam format mata uang dengan simbol dolar'),
  (136, 'DOLLARDE', '-', 'DOLLARDE(fractional_dollar, fraction)', 'Mengkonversi harga dolar dalam format pecahan menjadi desimal'),
  (137, 'DOLLARFR', '-', 'DOLLARFR(decimal_dollar, fraction)', 'Mengkonversi harga dolar dalam format desimal menjadi pecahan'),
  (138, 'DPRODUCT', '-', 'DPRODUCT(database, field, criteria)', 'Mengalikan nilai dalam kolom database yang cocok dengan kondisi'),
  (139, 'DROP', 'Excel 2024+', 'DROP(array, rows, [cols])', 'Menghapus sejumlah baris atau kolom dari awal atau akhir array'),
  (140, 'DSTDEV', '-', 'DSTDEV(database, field, criteria)', 'Menghitung deviasi standar sampel dari entri database yang cocok dengan kondisi'),
  (141, 'DSTDEVP', '-', 'DSTDEVP(database, field, criteria)', 'Menghitung deviasi standar populasi dari entri database yang cocok dengan kondisi'),
  (142, 'DSUM', '-', 'DSUM(database, field, criteria)', 'Menjumlahkan angka dalam kolom database yang cocok dengan kondisi'),
  (143, 'DURATION', '-', 'DURATION(settlement, maturity, coupon, yld, frequency, [basis])', 'Mengembalikan durasi Macauley tahunan untuk sekuritas dengan pembayaran bunga berkala'),
  (144, 'DVAR', '-', 'DVAR(database, field, criteria)', 'Menghitung varians berdasarkan sampel dari entri database yang cocok dengan kondisi'),
  (145, 'DVARP', '-', 'DVARP(database, field, criteria)', 'Menghitung varians berdasarkan populasi dari entri database yang cocok dengan kondisi'),
  (146, 'EDATE', '-', 'EDATE(start_date, months)', 'Mengembalikan angka seri tanggal yang merupakan jumlah bulan sebelum atau sesudah tanggal mulai'),
  (147, 'EFFECT', '-', 'EFFECT(nominal_rate, npery)', 'Mengembalikan tingkat bunga tahunan efektif'),
  (148, 'ENCODEURL', 'Excel 2013+', 'ENCODEURL(text)', 'Mengembalikan string yang dienkode sebagai URL'),
  (149, 'EOMONTH', '-', 'EOMONTH(start_date, months)', 'Mengembalikan nomor seri hari terakhir bulan sebelum atau sesudah sejumlah bulan'),
  (150, 'ERF', '-', 'ERF(lower_limit, [upper_limit])', 'Mengembalikan fungsi error'),
  (151, 'ERF.PRECISE', 'Excel 2010+', 'ERF.PRECISE(x)', 'Mengembalikan fungsi error yang diintegrasikan antara 0 dan x'),
  (152, 'ERFC', '-', 'ERFC(x)', 'Mengembalikan fungsi error komplementer'),
  (153, 'ERFC.PRECISE', 'Excel 2010+', 'ERFC.PRECISE(x)', 'Mengembalikan fungsi error komplementer yang diintegrasikan antara x dan tak terhingga'),
  (154, 'ERROR.TYPE', '-', 'ERROR.TYPE(error_val)', 'Mengembalikan angka yang sesuai dengan jenis error'),
  (155, 'EUROCONVERT', '-', 'EUROCONVERT(number, source, target, [full_precision], [triangulation_precision])', 'Mengkonversi angka ke Euro atau dari Euro ke mata uang Uni Eropa anggota'),
  (156, 'EVEN', '-', 'EVEN(number)', 'Membulatkan angka ke atas ke bilangan bulat genap terdekat'),
  (157, 'EXACT', '-', 'EXACT(text1, text2)', 'Memeriksa apakah dua string teks identis, peka huruf besar/kecil'),
  (158, 'EXP', '-', 'EXP(number)', 'Mengembalikan e dipangkatkan dengan angka yang diberikan'),
  (159, 'EXPAND', 'Excel 2024+', 'EXPAND(array, rows, [columns], [pad_with])', 'Memperluas atau mengisi array ke dimensi baris dan kolom yang ditentukan'),
  (160, 'EXPON.DIST', 'Excel 2010+', 'EXPON.DIST(x, lambda, cumulative)', 'Mengembalikan distribusi eksponensial'),
  (161, 'EXPONDIST', '-', 'EXPONDIST(x, lambda, cumulative)', 'Fungsi lama: Mengembalikan distribusi eksponensial (diganti EXPON.DIST)'),
  (162, 'FACT', '-', 'FACT(number)', 'Mengembalikan faktorial dari suatu angka'),
  (163, 'FACTDOUBLE', '-', 'FACTDOUBLE(number)', 'Mengembalikan faktorial ganda dari suatu angka'),
  (164, 'FALSE', '-', 'FALSE()', 'Mengembalikan nilai logika FALSE'),
  (165, 'F.DIST', 'Excel 2010+', 'F.DIST(x, deg_freedom1, deg_freedom2, cumulative)', 'Mengembalikan distribusi probabilitas F'),
  (166, 'FDIST', '-', 'FDIST(x, deg_freedom1, deg_freedom2)', 'Fungsi lama: Mengembalikan distribusi probabilitas F (diganti F.DIST.RT)'),
  (167, 'F.DIST.RT', 'Excel 2010+', 'F.DIST.RT(x, deg_freedom1, deg_freedom2)', 'Mengembalikan distribusi probabilitas F ekor kanan'),
  (168, 'FILTER', 'Excel 2021+', 'FILTER(array, include, [if_empty])', 'Memfilter rentang atau array berdasarkan kriteria yang ditentukan'),
  (169, 'FILTERXML', 'Excel 2013+', 'FILTERXML(xml, xpath)', 'Mengembalikan data spesifik dari konten XML menggunakan XPath yang ditentukan'),
  (170, 'FIND', '-', 'FIND(find_text, within_text, [start_num])', 'Menemukan string teks dalam string lain, peka huruf besar/kecil'),
  (171, 'FINDB', '-', 'FINDB(find_text, within_text, [start_num])', 'Menemukan string teks dalam string lain berdasarkan byte, peka huruf besar/kecil'),
  (172, 'F.INV', 'Excel 2010+', 'F.INV(probability, deg_freedom1, deg_freedom2)', 'Mengembalikan invers distribusi probabilitas F'),
  (173, 'F.INV.RT', 'Excel 2010+', 'F.INV.RT(probability, deg_freedom1, deg_freedom2)', 'Mengembalikan invers distribusi probabilitas F ekor kanan'),
  (174, 'FINV', '-', 'FINV(probability, deg_freedom1, deg_freedom2)', 'Fungsi lama: Mengembalikan invers distribusi F (diganti F.INV.RT)'),
  (175, 'FISHER', '-', 'FISHER(x)', 'Mengembalikan transformasi Fisher'),
  (176, 'FISHERINV', '-', 'FISHERINV(y)', 'Mengembalikan invers dari transformasi Fisher'),
  (177, 'FIXED', '-', 'FIXED(number, [decimals], [no_commas])', 'Memformat angka sebagai teks dengan jumlah desimal tetap'),
  (178, 'FLOOR', '-', 'FLOOR(number, significance)', 'Membulatkan angka ke bawah ke kelipatan signifikansi terdekat'),
  (179, 'FLOOR.MATH', 'Excel 2013+', 'FLOOR.MATH(number, [significance], [mode])', 'Membulatkan angka ke bawah ke bilangan bulat terdekat atau kelipatan signifikansi'),
  (180, 'FLOOR.PRECISE', '-', 'FLOOR.PRECISE(number, [significance])', 'Membulatkan angka ke bawah ke bilangan bulat atau kelipatan signifikansi terdekat'),
  (181, 'FORECAST', '-', 'FORECAST(x, known_ys, known_xs)', 'Fungsi lama: Menghitung nilai berdasarkan tren linear (diganti FORECAST.LINEAR)'),
  (182, 'FORECAST.ETS', 'Excel 2016+', 'FORECAST.ETS(target_date, values, timeline, [seasonality], [data_completion], [aggregation])', 'Mengembalikan nilai prediksi berdasarkan algoritma exponential smoothing (ETS)'),
  (183, 'FORECAST.ETS.CONFINT', 'Excel 2016+', 'FORECAST.ETS.CONFINT(target_date, values, timeline, [confidence_level], [seasonality], [data_completion], [aggregation])', 'Mengembalikan interval kepercayaan untuk nilai perkiraan pada tanggal target tertentu'),
  (184, 'FORECAST.ETS.SEASONALITY', 'Excel 2016+', 'FORECAST.ETS.SEASONALITY(values, timeline, [data_completion], [aggregation])', 'Mengembalikan panjang pola berulang yang terdeteksi oleh Excel untuk deret waktu tertentu'),
  (185, 'FORECAST.ETS.STAT', 'Excel 2016+', 'FORECAST.ETS.STAT(values, timeline, statistic_type, [seasonality], [data_completion], [aggregation])', 'Mengembalikan nilai statistik sebagai hasil perkiraan deret waktu'),
  (186, 'FORECAST.LINEAR', 'Excel 2016+', 'FORECAST.LINEAR(x, known_ys, known_xs)', 'Menghitung nilai berdasarkan tren linear'),
  (187, 'FORMULATEXT', 'Excel 2013+', 'FORMULATEXT(reference)', 'Mengembalikan rumus di referensi yang diberikan sebagai teks'),
  (188, 'FREQUENCY', '-', 'FREQUENCY(data_array, bins_array)', 'Menghitung seberapa sering nilai muncul dalam rentang nilai, mengembalikan array vertikal'),
  (189, 'F.TEST', 'Excel 2010+', 'F.TEST(array1, array2)', 'Mengembalikan hasil uji F, probabilitas bahwa varians array1 dan array2 tidak berbeda signifikan'),
  (190, 'FTEST', '-', 'FTEST(array1, array2)', 'Fungsi lama: Mengembalikan hasil uji F (diganti F.TEST)'),
  (191, 'FV', '-', 'FV(rate, nper, pmt, [pv], [type])', 'Mengembalikan nilai masa depan dari investasi'),
  (192, 'FVSCHEDULE', '-', 'FVSCHEDULE(principal, schedule)', 'Mengembalikan nilai masa depan dari pokok awal setelah menerapkan serangkaian tingkat bunga majemuk'),
  (193, 'GAMMA', 'Excel 2013+', 'GAMMA(number)', 'Mengembalikan nilai fungsi Gamma'),
  (194, 'GAMMA.DIST', 'Excel 2010+', 'GAMMA.DIST(x, alpha, beta, cumulative)', 'Mengembalikan distribusi gamma'),
  (195, 'GAMMADIST', '-', 'GAMMADIST(x, alpha, beta, cumulative)', 'Fungsi lama: Mengembalikan distribusi gamma (diganti GAMMA.DIST)'),
  (196, 'GAMMA.INV', 'Excel 2010+', 'GAMMA.INV(probability, alpha, beta)', 'Mengembalikan invers distribusi kumulatif gamma'),
  (197, 'GAMMAINV', '-', 'GAMMAINV(probability, alpha, beta)', 'Fungsi lama: Mengembalikan invers distribusi kumulatif gamma (diganti GAMMA.INV)'),
  (198, 'GAMMALN', '-', 'GAMMALN(x)', 'Mengembalikan logaritma natural dari fungsi gamma, Γ(x)'),
  (199, 'GAMMALN.PRECISE', 'Excel 2010+', 'GAMMALN.PRECISE(x)', 'Mengembalikan logaritma natural dari fungsi gamma, Γ(x) dengan presisi lebih tinggi'),
  (200, 'GAUSS', 'Excel 2013+', 'GAUSS(z)', 'Mengembalikan 0.5 lebih sedikit dari distribusi kumulatif normal standar');

INSERT INTO public.excel_formulas (no, nama_rumus, versi, syntax, penjelasan) VALUES
  (201, 'GCD', '-', 'GCD(number1, [number2], ...)', 'Mengembalikan pembagi persekutuan terbesar dari dua atau lebih bilangan bulat'),
  (202, 'GEOMEAN', '-', 'GEOMEAN(number1, [number2], ...)', 'Mengembalikan rata-rata geometrik dari array atau rentang data positif'),
  (203, 'GESTEP', '-', 'GESTEP(number, [step])', 'Menguji apakah angka lebih besar dari nilai ambang, mengembalikan 1 atau 0'),
  (204, 'GETPIVOTDATA', '-', 'GETPIVOTDATA(data_field, pivot_table, [field1, item1], ...)', 'Mengembalikan data yang tersimpan dalam laporan PivotTable'),
  (205, 'GROWTH', '-', 'GROWTH(known_ys, [known_xs], [new_xs], [const])', 'Mengembalikan nilai sesuai dengan tren eksponensial'),
  (206, 'HARMEAN', '-', 'HARMEAN(number1, [number2], ...)', 'Mengembalikan rata-rata harmonik dari kumpulan data'),
  (207, 'HEX2BIN', '-', 'HEX2BIN(number, [places])', 'Mengkonversi bilangan heksadesimal menjadi biner'),
  (208, 'HEX2DEC', '-', 'HEX2DEC(number)', 'Mengkonversi bilangan heksadesimal menjadi desimal'),
  (209, 'HEX2OCT', '-', 'HEX2OCT(number, [places])', 'Mengkonversi bilangan heksadesimal menjadi oktal'),
  (210, 'HLOOKUP', '-', 'HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])', 'Mencari nilai di baris pertama tabel dan mengembalikan nilai dari baris yang ditentukan'),
  (211, 'HOUR', '-', 'HOUR(serial_number)', 'Mengembalikan jam (0-23) dari nilai waktu'),
  (212, 'HSTACK', 'Excel 2024+', 'HSTACK(array1, [array2], ...)', 'Menggabungkan array secara horizontal dan berurutan untuk mengembalikan array yang lebih besar'),
  (213, 'HYPERLINK', '-', 'HYPERLINK(link_location, [friendly_name])', 'Membuat pintasan atau lompatan yang membuka dokumen pada lokasi tertentu'),
  (214, 'HYPGEOM.DIST', '-', 'HYPGEOM.DIST(sample_s, number_sample, population_s, number_pop, cumulative)', 'Mengembalikan distribusi hipergeometrik'),
  (215, 'HYPGEOMDIST', '-', 'HYPGEOMDIST(sample_s, number_sample, population_s, number_pop)', 'Fungsi lama: Mengembalikan distribusi hipergeometrik'),
  (216, 'IF', '-', 'IF(logical_test, [value_if_true], [value_if_false])', 'Melakukan tes logika dan mengembalikan satu nilai jika TRUE, nilai lain jika FALSE'),
  (217, 'IFERROR', '-', 'IFERROR(value, value_if_error)', 'Mengembalikan nilai yang ditentukan jika rumus menghasilkan error, sebaliknya mengembalikan hasil rumus'),
  (218, 'IFNA', 'Excel 2013+', 'IFNA(value, value_if_na)', 'Mengembalikan nilai yang ditentukan jika ekspresi menghasilkan #N/A, sebaliknya mengembalikan hasil ekspresi'),
  (219, 'IFS', 'Excel 2019+', 'IFS(logical_test1, value_if_true1, [logical_test2, value_if_true2], ...)', 'Memeriksa apakah satu atau lebih kondisi terpenuhi dan mengembalikan nilai yang sesuai'),
  (220, 'IMAGE', 'Excel 2024+', 'IMAGE(source, [alt_text], [sizing], [height], [width])', 'Menyisipkan gambar dari URL ke dalam sel'),
  (221, 'INDEX', '-', 'INDEX(array, row_num, [col_num])', 'Mengembalikan nilai atau referensi sel di persimpangan baris dan kolom tertentu'),
  (222, 'INDIRECT', '-', 'INDIRECT(ref_text, [a1])', 'Mengembalikan referensi yang ditentukan oleh string teks'),
  (223, 'INFO', '-', 'INFO(type_text)', 'Mengembalikan informasi tentang lingkungan operasi saat ini'),
  (224, 'INT', '-', 'INT(number)', 'Membulatkan angka ke bawah ke bilangan bulat terdekat'),
  (225, 'INTERCEPT', '-', 'INTERCEPT(known_ys, known_xs)', 'Menghitung titik perpotongan sumbu y dari garis regresi linear'),
  (226, 'INTRATE', '-', 'INTRATE(settlement, maturity, investment, redemption, [basis])', 'Mengembalikan tingkat bunga untuk sekuritas yang diinvestasikan penuh'),
  (227, 'IPMT', '-', 'IPMT(rate, per, nper, pv, [fv], [type])', 'Mengembalikan pembayaran bunga untuk investasi dalam periode tertentu'),
  (228, 'IRR', '-', 'IRR(values, [guess])', 'Mengembalikan tingkat pengembalian internal untuk serangkaian arus kas'),
  (229, 'ISBLANK', '-', 'ISBLANK(value)', 'Mengembalikan TRUE jika sel kosong'),
  (230, 'ISERR', '-', 'ISERR(value)', 'Mengembalikan TRUE jika nilai adalah error selain #N/A'),
  (231, 'ISERROR', '-', 'ISERROR(value)', 'Mengembalikan TRUE jika nilai adalah error apapun'),
  (232, 'ISEVEN', '-', 'ISEVEN(number)', 'Mengembalikan TRUE jika angka adalah genap'),
  (233, 'ISFORMULA', 'Excel 2013+', 'ISFORMULA(reference)', 'Mengembalikan TRUE jika ada referensi ke sel yang berisi rumus'),
  (234, 'ISLOGICAL', '-', 'ISLOGICAL(value)', 'Mengembalikan TRUE jika nilai adalah nilai logika'),
  (235, 'ISNA', '-', 'ISNA(value)', 'Mengembalikan TRUE jika nilai adalah #N/A error'),
  (236, 'ISNONTEXT', '-', 'ISNONTEXT(value)', 'Mengembalikan TRUE jika nilai bukan teks'),
  (237, 'ISNUMBER', '-', 'ISNUMBER(value)', 'Mengembalikan TRUE jika nilai adalah angka'),
  (238, 'ISODD', '-', 'ISODD(number)', 'Mengembalikan TRUE jika angka adalah ganjil'),
  (239, 'ISOMITTED', 'Excel 2024+', 'ISOMITTED(argument)', 'Memeriksa apakah nilai dalam fungsi LAMBDA hilang dan mengembalikan TRUE atau FALSE'),
  (240, 'ISREF', '-', 'ISREF(value)', 'Mengembalikan TRUE jika nilai adalah referensi'),
  (241, 'ISTEXT', '-', 'ISTEXT(value)', 'Mengembalikan TRUE jika nilai adalah teks'),
  (242, 'ISO.CEILING', 'Excel 2013+', 'ISO.CEILING(number, [significance])', 'Mengembalikan angka yang dibulatkan ke atas ke bilangan bulat atau kelipatan signifikansi terdekat'),
  (243, 'ISOWEEKNUM', 'Excel 2013+', 'ISOWEEKNUM(date)', 'Mengembalikan nomor minggu ISO dari tahun untuk tanggal tertentu'),
  (244, 'ISPMT', '-', 'ISPMT(rate, per, nper, pv)', 'Menghitung bunga yang dibayarkan selama periode tertentu dari investasi'),
  (245, 'KURT', '-', 'KURT(number1, [number2], ...)', 'Mengembalikan kurtosis dari kumpulan data'),
  (246, 'LAMBDA', 'Excel 2024+', 'LAMBDA([parameter1, ...], calculation)', 'Membuat fungsi lambda kustom yang dapat digunakan kembali'),
  (247, 'LARGE', '-', 'LARGE(array, k)', 'Mengembalikan nilai terbesar ke-k dalam kumpulan data'),
  (248, 'LCM', '-', 'LCM(number1, [number2], ...)', 'Mengembalikan kelipatan persekutuan terkecil dari bilangan bulat'),
  (249, 'LEFT', '-', 'LEFT(text, [num_chars])', 'Mengembalikan karakter pertama atau beberapa karakter pertama dari string teks'),
  (250, 'LEFTB', '-', 'LEFTB(text, [num_bytes])', 'Mengembalikan karakter pertama dari string teks berdasarkan jumlah byte'),
  (251, 'LEN', '-', 'LEN(text)', 'Mengembalikan jumlah karakter dalam string teks'),
  (252, 'LENB', '-', 'LENB(text)', 'Mengembalikan jumlah byte dalam string teks'),
  (253, 'LET', 'Excel 2021+', 'LET(name1, name_value1, [name2/name_value2], ..., calculation)', 'Menetapkan nama pada hasil perhitungan dan menyimpannya sebagai variabel sementara'),
  (254, 'LINEST', '-', 'LINEST(known_ys, [known_xs], [const], [stats])', 'Menghitung statistik untuk garis menggunakan metode least squares'),
  (255, 'LN', '-', 'LN(number)', 'Mengembalikan logaritma natural dari suatu angka'),
  (256, 'LOG', '-', 'LOG(number, [base])', 'Mengembalikan logaritma dari suatu angka dengan basis yang ditentukan'),
  (257, 'LOG10', '-', 'LOG10(number)', 'Mengembalikan logaritma basis 10 dari suatu angka'),
  (258, 'LOGEST', '-', 'LOGEST(known_ys, [known_xs], [const], [stats])', 'Menghitung kurva eksponensial yang paling cocok untuk data'),
  (259, 'LOGINV', '-', 'LOGINV(probability, mean, standard_dev)', 'Fungsi lama: Mengembalikan invers distribusi lognormal kumulatif (diganti LOGNORM.INV)'),
  (260, 'LOGNORM.DIST', 'Excel 2010+', 'LOGNORM.DIST(x, mean, standard_dev, cumulative)', 'Mengembalikan distribusi lognormal kumulatif'),
  (261, 'LOGNORMDIST', '-', 'LOGNORMDIST(x, mean, standard_dev)', 'Fungsi lama: Mengembalikan distribusi lognormal kumulatif'),
  (262, 'LOGNORM.INV', 'Excel 2010+', 'LOGNORM.INV(probability, mean, standard_dev)', 'Mengembalikan invers dari distribusi lognormal kumulatif'),
  (263, 'LOOKUP', '-', 'LOOKUP(lookup_value, lookup_vector, [result_vector])', 'Mencari nilai dalam vektor atau array (mode vektor atau array)'),
  (264, 'LOWER', '-', 'LOWER(text)', 'Mengkonversi semua huruf dalam string teks menjadi huruf kecil'),
  (265, 'MAKEARRAY', 'Excel 2024+', 'MAKEARRAY(rows, cols, lambda)', 'Mengembalikan array dengan ukuran yang ditentukan dengan menerapkan LAMBDA'),
  (266, 'MAP', 'Excel 2024+', 'MAP(array1, [array2], ..., lambda)', 'Mengembalikan array yang terbentuk dengan memetakan setiap nilai ke nilai baru menggunakan LAMBDA'),
  (267, 'MATCH', '-', 'MATCH(lookup_value, lookup_array, [match_type])', 'Mencari nilai tertentu dalam rentang sel, dan mengembalikan posisi relatif nilai tersebut'),
  (268, 'MAX', '-', 'MAX(number1, [number2], ...)', 'Mengembalikan nilai terbesar dalam kumpulan nilai'),
  (269, 'MAXA', '-', 'MAXA(value1, [value2], ...)', 'Mengembalikan nilai terbesar dalam kumpulan nilai, termasuk angka, teks, dan nilai logika'),
  (270, 'MAXIFS', 'Excel 2019+', 'MAXIFS(max_range, criteria_range1, criteria1, ...)', 'Mengembalikan nilai maksimum di antara sel yang memenuhi beberapa kriteria'),
  (271, 'MDETERM', '-', 'MDETERM(array)', 'Mengembalikan determinan matriks dari array'),
  (272, 'MDURATION', '-', 'MDURATION(settlement, maturity, coupon, yld, frequency, [basis])', 'Mengembalikan durasi Macauley yang dimodifikasi untuk sekuritas'),
  (273, 'MEDIAN', '-', 'MEDIAN(number1, [number2], ...)', 'Mengembalikan nilai tengah dari kumpulan angka'),
  (274, 'MID', '-', 'MID(text, start_num, num_chars)', 'Mengembalikan sejumlah karakter tertentu dari string teks, mulai dari posisi yang ditentukan'),
  (275, 'MIDB', '-', 'MIDB(text, start_num, num_bytes)', 'Mengembalikan karakter tertentu dari string teks berdasarkan byte'),
  (276, 'MIN', '-', 'MIN(number1, [number2], ...)', 'Mengembalikan nilai terkecil dalam kumpulan nilai'),
  (277, 'MINIFS', 'Excel 2019+', 'MINIFS(min_range, criteria_range1, criteria1, ...)', 'Mengembalikan nilai minimum di antara sel yang memenuhi beberapa kriteria'),
  (278, 'MINA', '-', 'MINA(value1, [value2], ...)', 'Mengembalikan nilai terkecil dalam kumpulan nilai, termasuk angka, teks, dan nilai logika'),
  (279, 'MINUTE', '-', 'MINUTE(serial_number)', 'Mengembalikan menit (0-59) dari nilai waktu'),
  (280, 'MINVERSE', '-', 'MINVERSE(array)', 'Mengembalikan matriks invers dari array'),
  (281, 'MIRR', '-', 'MIRR(values, finance_rate, reinvest_rate)', 'Mengembalikan tingkat pengembalian internal yang dimodifikasi untuk serangkaian arus kas'),
  (282, 'MMULT', '-', 'MMULT(array1, array2)', 'Mengembalikan perkalian matriks dari dua array'),
  (283, 'MOD', '-', 'MOD(number, divisor)', 'Mengembalikan sisa pembagian dari suatu angka'),
  (284, 'MODE', '-', 'MODE(number1, [number2], ...)', 'Fungsi lama: Mengembalikan nilai yang paling sering muncul (diganti MODE.SNGL)'),
  (285, 'MODE.MULT', 'Excel 2010+', 'MODE.MULT(number1, [number2], ...)', 'Mengembalikan array vertikal dari nilai yang paling sering muncul dalam array atau rentang data'),
  (286, 'MODE.SNGL', 'Excel 2010+', 'MODE.SNGL(number1, [number2], ...)', 'Mengembalikan nilai yang paling sering muncul dalam array atau rentang data'),
  (287, 'MONTH', '-', 'MONTH(serial_number)', 'Mengembalikan bulan (1-12) dari suatu tanggal'),
  (288, 'MROUND', '-', 'MROUND(number, multiple)', 'Mengembalikan angka yang dibulatkan ke kelipatan yang diinginkan'),
  (289, 'MULTINOMIAL', '-', 'MULTINOMIAL(number1, [number2], ...)', 'Mengembalikan rasio faktorial dari jumlah nilai terhadap produk faktorial'),
  (290, 'MUNIT', 'Excel 2013+', 'MUNIT(dimension)', 'Mengembalikan matriks satuan atau dimensi yang ditentukan'),
  (291, 'N', '-', 'N(value)', 'Mengembalikan nilai yang dikonversi ke angka'),
  (292, 'NA', '-', 'NA()', 'Mengembalikan nilai error #N/A'),
  (293, 'NEGBINOM.DIST', 'Excel 2010+', 'NEGBINOM.DIST(number_f, number_s, probability_s, cumulative)', 'Mengembalikan distribusi binomial negatif'),
  (294, 'NEGBINOMDIST', '-', 'NEGBINOMDIST(number_f, number_s, probability_s)', 'Fungsi lama: Mengembalikan distribusi binomial negatif'),
  (295, 'NETWORKDAYS', '-', 'NETWORKDAYS(start_date, end_date, [holidays])', 'Mengembalikan jumlah hari kerja antara dua tanggal'),
  (296, 'NETWORKDAYS.INTL', 'Excel 2010+', 'NETWORKDAYS.INTL(start_date, end_date, [weekend], [holidays])', 'Mengembalikan jumlah hari kerja antara dua tanggal dengan parameter akhir pekan kustom'),
  (297, 'NOMINAL', '-', 'NOMINAL(effect_rate, npery)', 'Mengembalikan tingkat bunga nominal tahunan'),
  (298, 'NORM.DIST', 'Excel 2010+', 'NORM.DIST(x, mean, standard_dev, cumulative)', 'Mengembalikan distribusi normal'),
  (299, 'NORMDIST', '-', 'NORMDIST(x, mean, standard_dev, cumulative)', 'Fungsi lama: Mengembalikan distribusi normal kumulatif (diganti NORM.DIST)'),
  (300, 'NORMINV', '-', 'NORMINV(probability, mean, standard_dev)', 'Fungsi lama: Mengembalikan invers distribusi normal kumulatif (diganti NORM.INV)');

INSERT INTO public.excel_formulas (no, nama_rumus, versi, syntax, penjelasan) VALUES
  (301, 'NORM.INV', 'Excel 2010+', 'NORM.INV(probability, mean, standard_dev)', 'Mengembalikan invers dari distribusi kumulatif normal'),
  (302, 'NORM.S.DIST', 'Excel 2010+', 'NORM.S.DIST(z, cumulative)', 'Mengembalikan distribusi normal standar'),
  (303, 'NORMSDIST', '-', 'NORMSDIST(z)', 'Fungsi lama: Mengembalikan distribusi normal standar kumulatif (diganti NORM.S.DIST)'),
  (304, 'NORM.S.INV', 'Excel 2010+', 'NORM.S.INV(probability)', 'Mengembalikan invers dari distribusi kumulatif normal standar'),
  (305, 'NORMSINV', '-', 'NORMSINV(probability)', 'Fungsi lama: Mengembalikan invers dari distribusi kumulatif normal standar (diganti NORM.S.INV)'),
  (306, 'NOT', '-', 'NOT(logical)', 'Membalikkan logika argumennya'),
  (307, 'NOW', '-', 'NOW()', 'Mengembalikan tanggal dan waktu saat ini'),
  (308, 'NPER', '-', 'NPER(rate, pmt, pv, [fv], [type])', 'Mengembalikan jumlah periode untuk investasi'),
  (309, 'NPV', '-', 'NPV(rate, value1, [value2], ...)', 'Menghitung nilai sekarang bersih dari investasi berdasarkan tingkat diskonto dan serangkaian arus kas masa depan'),
  (310, 'NUMBERVALUE', 'Excel 2013+', 'NUMBERVALUE(text, [decimal_separator], [group_separator])', 'Mengkonversi teks menjadi angka secara independen dari locale'),
  (311, 'OCT2BIN', '-', 'OCT2BIN(number, [places])', 'Mengkonversi bilangan oktal menjadi biner'),
  (312, 'OCT2DEC', '-', 'OCT2DEC(number)', 'Mengkonversi bilangan oktal menjadi desimal'),
  (313, 'OCT2HEX', '-', 'OCT2HEX(number, [places])', 'Mengkonversi bilangan oktal menjadi heksadesimal'),
  (314, 'ODD', '-', 'ODD(number)', 'Membulatkan angka ke atas ke bilangan bulat ganjil terdekat'),
  (315, 'ODDFPRICE', '-', 'ODDFPRICE(settlement, maturity, issue, first_coupon, rate, yld, redemption, frequency, [basis])', 'Mengembalikan harga per nilai nominal $100 sekuritas dengan periode pertama yang tidak beraturan'),
  (316, 'ODDFYIELD', '-', 'ODDFYIELD(settlement, maturity, issue, first_coupon, rate, pr, redemption, frequency, [basis])', 'Mengembalikan imbal hasil sekuritas dengan periode pertama yang tidak beraturan'),
  (317, 'ODDLPRICE', '-', 'ODDLPRICE(settlement, maturity, last_interest, rate, yld, redemption, frequency, [basis])', 'Mengembalikan harga per nilai nominal $100 sekuritas dengan periode terakhir yang tidak beraturan'),
  (318, 'ODDLYIELD', '-', 'ODDLYIELD(settlement, maturity, last_interest, rate, pr, redemption, frequency, [basis])', 'Mengembalikan imbal hasil sekuritas dengan periode terakhir yang tidak beraturan'),
  (319, 'OFFSET', '-', 'OFFSET(reference, rows, cols, [height], [width])', 'Mengembalikan referensi yang diimbangi dari referensi yang diberikan'),
  (320, 'OR', '-', 'OR(logical1, [logical2], ...)', 'Mengembalikan TRUE jika salah satu argumen bernilai TRUE'),
  (321, 'PDURATION', 'Excel 2013+', 'PDURATION(rate, pv, fv)', 'Mengembalikan jumlah periode yang diperlukan investasi untuk mencapai nilai tertentu'),
  (322, 'PEARSON', '-', 'PEARSON(array1, array2)', 'Mengembalikan koefisien korelasi momen produk Pearson'),
  (323, 'PERCENTILE.EXC', 'Excel 2010+', 'PERCENTILE.EXC(array, k)', 'Mengembalikan persentil ke-k dari nilai dalam rentang, dimana k dalam rentang 0..1 eksklusif'),
  (324, 'PERCENTILE.INC', 'Excel 2010+', 'PERCENTILE.INC(array, k)', 'Mengembalikan persentil ke-k dari nilai dalam rentang'),
  (325, 'PERCENTILE', '-', 'PERCENTILE(array, k)', 'Fungsi lama: Mengembalikan persentil ke-k dari nilai dalam rentang (diganti PERCENTILE.INC)'),
  (326, 'PERCENTRANK.EXC', 'Excel 2010+', 'PERCENTRANK.EXC(array, x, [significance])', 'Mengembalikan peringkat suatu nilai dalam kumpulan data sebagai persentase (0..1 eksklusif)'),
  (327, 'PERCENTRANK.INC', 'Excel 2010+', 'PERCENTRANK.INC(array, x, [significance])', 'Mengembalikan peringkat suatu nilai dalam kumpulan data sebagai persentase'),
  (328, 'PERCENTRANK', '-', 'PERCENTRANK(array, x, [significance])', 'Fungsi lama: Mengembalikan peringkat persentase nilai dalam kumpulan data (diganti PERCENTRANK.INC)'),
  (329, 'PERMUT', '-', 'PERMUT(number, number_chosen)', 'Mengembalikan jumlah permutasi untuk sejumlah objek tertentu'),
  (330, 'PERMUTATIONA', 'Excel 2013+', 'PERMUTATIONA(number, number_chosen)', 'Mengembalikan jumlah permutasi untuk sejumlah objek (dengan pengulangan)'),
  (331, 'PHI', 'Excel 2013+', 'PHI(x)', 'Mengembalikan nilai fungsi kerapatan untuk distribusi normal standar'),
  (332, 'PI', '-', 'PI()', 'Mengembalikan nilai Pi (3,14159265358979...)'),
  (333, 'PMT', '-', 'PMT(rate, nper, pv, [fv], [type])', 'Menghitung pembayaran periodik untuk pinjaman atau investasi'),
  (334, 'POISSON.DIST', 'Excel 2010+', 'POISSON.DIST(x, mean, cumulative)', 'Mengembalikan distribusi Poisson'),
  (335, 'POISSON', '-', 'POISSON(x, mean, cumulative)', 'Fungsi lama: Mengembalikan distribusi Poisson (diganti POISSON.DIST)'),
  (336, 'POWER', '-', 'POWER(number, power)', 'Mengembalikan hasil angka yang dipangkatkan'),
  (337, 'PPMT', '-', 'PPMT(rate, per, nper, pv, [fv], [type])', 'Mengembalikan pembayaran pokok untuk periode tertentu'),
  (338, 'PRICE', '-', 'PRICE(settlement, maturity, rate, yld, redemption, frequency, [basis])', 'Mengembalikan harga per nilai nominal $100 dari sekuritas yang membayar bunga berkala'),
  (339, 'PRICEDISC', '-', 'PRICEDISC(settlement, maturity, discount, redemption, [basis])', 'Mengembalikan harga per nilai nominal $100 sekuritas berdiskon'),
  (340, 'PRICEMAT', '-', 'PRICEMAT(settlement, maturity, issue, rate, yld, [basis])', 'Mengembalikan harga per nilai nominal $100 sekuritas yang membayar bunga pada saat jatuh tempo'),
  (341, 'PROB', '-', 'PROB(x_range, prob_range, [lower_limit], [upper_limit])', 'Mengembalikan probabilitas bahwa nilai dalam suatu rentang berada di antara dua batas'),
  (342, 'PRODUCT', '-', 'PRODUCT(number1, [number2], ...)', 'Mengalikan semua angka yang diberikan sebagai argumen dan mengembalikan produknya'),
  (343, 'PROPER', '-', 'PROPER(text)', 'Mengkonversi huruf pertama setiap kata menjadi huruf kapital'),
  (344, 'PV', '-', 'PV(rate, nper, pmt, [fv], [type])', 'Mengembalikan nilai sekarang dari investasi'),
  (345, 'QUARTILE', '-', 'QUARTILE(array, quart)', 'Fungsi lama: Mengembalikan kuartil dari kumpulan data (diganti QUARTILE.INC)'),
  (346, 'QUARTILE.EXC', 'Excel 2010+', 'QUARTILE.EXC(array, quart)', 'Mengembalikan kuartil dari kumpulan data berdasarkan nilai persentil dari 0..1 eksklusif'),
  (347, 'QUARTILE.INC', 'Excel 2010+', 'QUARTILE.INC(array, quart)', 'Mengembalikan kuartil dari kumpulan data'),
  (348, 'QUOTIENT', '-', 'QUOTIENT(numerator, denominator)', 'Mengembalikan bagian bilangan bulat dari pembagian'),
  (349, 'RADIANS', '-', 'RADIANS(angle)', 'Mengkonversi derajat menjadi radian'),
  (350, 'RAND', '-', 'RAND()', 'Mengembalikan angka acak antara 0 dan 1 (akan berubah setiap kalkulasi ulang)'),
  (351, 'RANDARRAY', 'Excel 2021+', 'RANDARRAY([rows], [cols], [min], [max], [whole_number])', 'Mengembalikan array angka acak antara 0 dan 1'),
  (352, 'RANDBETWEEN', '-', 'RANDBETWEEN(bottom, top)', 'Mengembalikan angka acak antara angka yang ditentukan'),
  (353, 'RANK.AVG', 'Excel 2010+', 'RANK.AVG(number, ref, [order])', 'Mengembalikan peringkat angka dalam daftar angka, jika ada nilai yang sama akan dirata-rata'),
  (354, 'RANK.EQ', 'Excel 2010+', 'RANK.EQ(number, ref, [order])', 'Mengembalikan peringkat angka dalam daftar angka'),
  (355, 'RANK', '-', 'RANK(number, ref, [order])', 'Fungsi lama: Mengembalikan peringkat angka dalam daftar (diganti RANK.EQ)'),
  (356, 'RATE', '-', 'RATE(nper, pmt, pv, [fv], [type], [guess])', 'Mengembalikan tingkat bunga per periode dari anuitas'),
  (357, 'RECEIVED', '-', 'RECEIVED(settlement, maturity, investment, discount, [basis])', 'Mengembalikan jumlah yang diterima pada saat jatuh tempo untuk sekuritas yang diinvestasikan penuh'),
  (358, 'REDUCE', 'Excel 2024+', 'REDUCE([initial_value], array, lambda)', 'Mereduksi array menjadi nilai akumulasi dengan menerapkan LAMBDA ke setiap nilai'),
  (359, 'REPLACE', '-', 'REPLACE(old_text, start_num, num_chars, new_text)', 'Mengganti bagian string teks dengan string teks yang berbeda'),
  (360, 'REPLACEB', '-', 'REPLACEB(old_text, start_num, num_bytes, new_text)', 'Mengganti bagian string teks berdasarkan byte'),
  (361, 'REPT', '-', 'REPT(text, number_times)', 'Mengulang teks sejumlah kali tertentu'),
  (362, 'RIGHT', '-', 'RIGHT(text, [num_chars])', 'Mengembalikan karakter terakhir dari string teks'),
  (363, 'RIGHTB', '-', 'RIGHTB(text, [num_bytes])', 'Mengembalikan karakter terakhir dari string teks berdasarkan byte'),
  (364, 'ROMAN', '-', 'ROMAN(number, [form])', 'Mengkonversi angka Arab menjadi angka Romawi dalam format teks'),
  (365, 'ROUND', '-', 'ROUND(number, num_digits)', 'Membulatkan angka ke sejumlah digit yang ditentukan'),
  (366, 'ROUNDDOWN', '-', 'ROUNDDOWN(number, num_digits)', 'Membulatkan angka ke bawah menuju nol'),
  (367, 'ROUNDUP', '-', 'ROUNDUP(number, num_digits)', 'Membulatkan angka ke atas menjauh dari nol'),
  (368, 'ROW', '-', 'ROW([reference])', 'Mengembalikan nomor baris dari suatu referensi'),
  (369, 'ROWS', '-', 'ROWS(array)', 'Mengembalikan jumlah baris dalam suatu array atau referensi'),
  (370, 'RRI', 'Excel 2013+', 'RRI(nper, pv, fv)', 'Mengembalikan suku bunga ekuivalen untuk pertumbuhan investasi'),
  (371, 'RSQ', '-', 'RSQ(known_ys, known_xs)', 'Mengembalikan kuadrat koefisien korelasi momen produk Pearson'),
  (372, 'SCAN', 'Excel 2024+', 'SCAN([initial_value], array, lambda)', 'Memindai array dengan menerapkan LAMBDA ke setiap nilai dan mengembalikan array yang memiliki setiap nilai sementara'),
  (373, 'SEARCH', '-', 'SEARCH(find_text, within_text, [start_num])', 'Menemukan teks dalam teks lain, tidak peka huruf besar/kecil'),
  (374, 'SEARCHB', '-', 'SEARCHB(find_text, within_text, [start_num])', 'Menemukan teks dalam teks lain berdasarkan byte, tidak peka huruf besar/kecil'),
  (375, 'SEC', 'Excel 2013+', 'SEC(number)', 'Mengembalikan sekan dari suatu sudut dalam radian'),
  (376, 'SECH', 'Excel 2013+', 'SECH(number)', 'Mengembalikan sekan hiperbolik dari suatu sudut'),
  (377, 'SECOND', '-', 'SECOND(serial_number)', 'Mengembalikan detik (0-59) dari nilai waktu'),
  (378, 'SEQUENCE', 'Excel 2021+', 'SEQUENCE(rows, [cols], [start], [step])', 'Menghasilkan daftar angka berurutan dalam array'),
  (379, 'SERIESSUM', '-', 'SERIESSUM(x, n, m, coefficients)', 'Mengembalikan jumlah deret pangkat berdasarkan rumus'),
  (380, 'SHEET', 'Excel 2013+', 'SHEET(value)', 'Mengembalikan nomor lembar dari lembar yang direferensikan'),
  (381, 'SHEETS', 'Excel 2013+', 'SHEETS([reference])', 'Mengembalikan jumlah lembar dalam referensi'),
  (382, 'SIGN', '-', 'SIGN(number)', 'Mengembalikan tanda suatu angka: 1 jika positif, 0 jika nol, -1 jika negatif'),
  (383, 'SIN', '-', 'SIN(number)', 'Mengembalikan sinus dari suatu sudut dalam radian'),
  (384, 'SINH', '-', 'SINH(number)', 'Mengembalikan sinus hiperbolik dari suatu angka'),
  (385, 'SKEW', '-', 'SKEW(number1, [number2], ...)', 'Mengembalikan kemencengan distribusi'),
  (386, 'SKEW.P', 'Excel 2013+', 'SKEW.P(number1, [number2], ...)', 'Mengembalikan kemencengan distribusi berdasarkan populasi'),
  (387, 'SLN', '-', 'SLN(cost, salvage, life)', 'Mengembalikan penyusutan garis lurus aset untuk satu periode'),
  (388, 'SLOPE', '-', 'SLOPE(known_ys, known_xs)', 'Mengembalikan kemiringan garis regresi linear'),
  (389, 'SMALL', '-', 'SMALL(array, k)', 'Mengembalikan nilai terkecil ke-k dalam kumpulan data'),
  (390, 'SORT', 'Excel 2021+', 'SORT(array, [sort_index], [sort_order], [by_col])', 'Mengurutkan isi rentang atau array'),
  (391, 'SORTBY', 'Excel 2021+', 'SORTBY(array, by_array1, [sort_order1], ...)', 'Mengurutkan isi rentang atau array berdasarkan nilai dalam rentang atau array yang sesuai'),
  (392, 'SQRT', '-', 'SQRT(number)', 'Mengembalikan akar kuadrat positif'),
  (393, 'SQRTPI', '-', 'SQRTPI(number)', 'Mengembalikan akar kuadrat dari (angka * pi)'),
  (394, 'STANDARDIZE', '-', 'STANDARDIZE(x, mean, standard_dev)', 'Mengembalikan nilai yang ternormalisasi dari distribusi yang ditandai dengan mean dan standar deviasi'),
  (395, 'STDEV', '-', 'STDEV(number1, [number2], ...)', 'Fungsi lama: Menghitung deviasi standar berdasarkan sampel (diganti STDEV.S)'),
  (396, 'STDEV.P', 'Excel 2010+', 'STDEV.P(number1, [number2], ...)', 'Menghitung deviasi standar berdasarkan seluruh populasi'),
  (397, 'STDEV.S', 'Excel 2010+', 'STDEV.S(number1, [number2], ...)', 'Menghitung deviasi standar berdasarkan sampel'),
  (398, 'STDEVA', '-', 'STDEVA(value1, [value2], ...)', 'Menghitung deviasi standar berdasarkan sampel, termasuk angka, teks, dan nilai logika'),
  (399, 'STDEVP', '-', 'STDEVP(number1, [number2], ...)', 'Fungsi lama: Menghitung deviasi standar berdasarkan populasi (diganti STDEV.P)'),
  (400, 'STDEVPA', '-', 'STDEVPA(value1, [value2], ...)', 'Menghitung deviasi standar berdasarkan populasi, termasuk angka, teks, dan nilai logika');

INSERT INTO public.excel_formulas (no, nama_rumus, versi, syntax, penjelasan) VALUES
  (401, 'STEYX', '-', 'STEYX(known_ys, known_xs)', 'Mengembalikan galat standar nilai y yang diprediksi untuk setiap x dalam regresi'),
  (402, 'SUBSTITUTE', '-', 'SUBSTITUTE(text, old_text, new_text, [instance_num])', 'Mengganti teks lama dengan teks baru dalam string teks'),
  (403, 'SUBTOTAL', '-', 'SUBTOTAL(function_num, ref1, [ref2], ...)', 'Mengembalikan subtotal dalam daftar atau database'),
  (404, 'SUM', '-', 'SUM(number1, [number2], ...)', 'Menjumlahkan semua angka dalam rentang sel'),
  (405, 'SUMIF', '-', 'SUMIF(range, criteria, [sum_range])', 'Menjumlahkan sel yang memenuhi satu kriteria tertentu'),
  (406, 'SUMIFS', '-', 'SUMIFS(sum_range, criteria_range1, criteria1, ...)', 'Menjumlahkan sel yang memenuhi beberapa kriteria'),
  (407, 'SUMPRODUCT', '-', 'SUMPRODUCT(array1, [array2], ...)', 'Mengalikan komponen yang sesuai dalam array dan mengembalikan jumlah produk'),
  (408, 'SUMSQ', '-', 'SUMSQ(number1, [number2], ...)', 'Mengembalikan jumlah kuadrat dari argumen'),
  (409, 'SUMX2MY2', '-', 'SUMX2MY2(array_x, array_y)', 'Mengembalikan jumlah selisih kuadrat dari nilai yang bersesuaian dalam dua array'),
  (410, 'SUMX2PY2', '-', 'SUMX2PY2(array_x, array_y)', 'Mengembalikan jumlah kuadrat dari nilai yang bersesuaian dalam dua array'),
  (411, 'SUMXMY2', '-', 'SUMXMY2(array_x, array_y)', 'Mengembalikan jumlah kuadrat selisih dari nilai yang bersesuaian dalam dua array'),
  (412, 'SWITCH', 'Excel 2019+', 'SWITCH(expression, value1, result1, [value2, result2], ..., [default])', 'Mengevaluasi ekspresi terhadap daftar nilai dan mengembalikan hasil yang sesuai dengan nilai pertama yang cocok'),
  (413, 'SYD', '-', 'SYD(cost, salvage, life, per)', 'Mengembalikan penyusutan jumlah-digit tahun dari aset untuk periode tertentu'),
  (414, 'T', '-', 'T(value)', 'Mengembalikan teks yang dirujuk oleh nilai atau string kosong jika bukan teks'),
  (415, 'TAN', '-', 'TAN(number)', 'Mengembalikan tangen dari suatu sudut dalam radian'),
  (416, 'TANH', '-', 'TANH(number)', 'Mengembalikan tangen hiperbolik dari suatu angka'),
  (417, 'TAKE', 'Excel 2024+', 'TAKE(array, rows, [cols])', 'Mengembalikan sejumlah baris atau kolom yang berurutan dari awal atau akhir array'),
  (418, 'TBILLEQ', '-', 'TBILLEQ(settlement, maturity, discount)', 'Mengembalikan imbal hasil setara obligasi untuk Surat Perbendaharaan Negara'),
  (419, 'TBILLPRICE', '-', 'TBILLPRICE(settlement, maturity, discount)', 'Mengembalikan harga per nilai nominal $100 untuk Surat Perbendaharaan Negara'),
  (420, 'TBILLYIELD', '-', 'TBILLYIELD(settlement, maturity, pr)', 'Mengembalikan imbal hasil untuk Surat Perbendaharaan Negara'),
  (421, 'T.DIST', 'Excel 2010+', 'T.DIST(x, deg_freedom, cumulative)', 'Mengembalikan distribusi t-Student'),
  (422, 'T.DIST.2T', 'Excel 2010+', 'T.DIST.2T(x, deg_freedom)', 'Mengembalikan distribusi t-Student dua ekor'),
  (423, 'T.DIST.RT', 'Excel 2010+', 'T.DIST.RT(x, deg_freedom)', 'Mengembalikan distribusi t-Student ekor kanan'),
  (424, 'TDIST', '-', 'TDIST(x, deg_freedom, tails)', 'Fungsi lama: Mengembalikan distribusi t-Student (diganti T.DIST)'),
  (425, 'TEXT', '-', 'TEXT(value, format_text)', 'Mengkonversi angka menjadi teks dalam format angka tertentu'),
  (426, 'TEXTAFTER', 'Excel 2024+', 'TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])', 'Mengembalikan teks yang muncul setelah karakter atau string yang diberikan'),
  (427, 'TEXTBEFORE', 'Excel 2024+', 'TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])', 'Mengembalikan teks yang muncul sebelum karakter atau string yang diberikan'),
  (428, 'TEXTJOIN', 'Excel 2019+', 'TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)', 'Menggabungkan teks dari beberapa rentang dan/atau string, memisahkan setiap item teks dengan pembatas'),
  (429, 'TEXTSPLIT', 'Excel 2024+', 'TEXTSPLIT(input_text, [col_delimiter], [row_delimiter], [ignore_empty], [match_mode], [pad_with])', 'Memisahkan string teks menggunakan kolom dan baris pembatas'),
  (430, 'TIME', '-', 'TIME(hour, minute, second)', 'Mengembalikan angka seri yang mewakili waktu tertentu'),
  (431, 'TIMEVALUE', '-', 'TIMEVALUE(time_text)', 'Mengkonversi waktu dalam bentuk teks menjadi angka seri'),
  (432, 'T.INV', 'Excel 2010+', 'T.INV(probability, deg_freedom)', 'Mengembalikan invers distribusi t-Student ekor kiri'),
  (433, 'T.INV.2T', 'Excel 2010+', 'T.INV.2T(probability, deg_freedom)', 'Mengembalikan invers distribusi t-Student dua ekor'),
  (434, 'TINV', '-', 'TINV(probability, deg_freedom)', 'Fungsi lama: Mengembalikan invers distribusi t-Student (diganti T.INV.2T)'),
  (435, 'TOCOL', 'Excel 2024+', 'TOCOL(array, [ignore], [scan_by_column])', 'Mengembalikan array dalam satu kolom'),
  (436, 'TOROW', 'Excel 2024+', 'TOROW(array, [ignore], [scan_by_column])', 'Mengembalikan array dalam satu baris'),
  (437, 'TODAY', '-', 'TODAY()', 'Mengembalikan tanggal saat ini'),
  (438, 'TRANSPOSE', '-', 'TRANSPOSE(array)', 'Mengembalikan transpos array atau rentang sel vertikal sebagai rentang horizontal'),
  (439, 'TREND', '-', 'TREND(known_ys, [known_xs], [new_xs], [const])', 'Mengembalikan nilai sepanjang tren linear'),
  (440, 'TRIM', '-', 'TRIM(text)', 'Menghapus semua spasi dari teks kecuali spasi tunggal antar kata'),
  (441, 'TRIMMEAN', '-', 'TRIMMEAN(array, percent)', 'Mengembalikan rata-rata dari bagian dalam kumpulan data, mengecualikan persentase titik data dari atas dan bawah'),
  (442, 'TRUE', '-', 'TRUE()', 'Mengembalikan nilai logika TRUE'),
  (443, 'TRUNC', '-', 'TRUNC(number, [num_digits])', 'Memotong angka menjadi bilangan bulat dengan menghapus bagian desimal'),
  (444, 'T.TEST', 'Excel 2010+', 'T.TEST(array1, array2, tails, type)', 'Mengembalikan probabilitas yang terkait dengan uji t-Student'),
  (445, 'TTEST', '-', 'TTEST(array1, array2, tails, type)', 'Fungsi lama: Mengembalikan probabilitas yang terkait dengan uji t-Student (diganti T.TEST)'),
  (446, 'TYPE', '-', 'TYPE(value)', 'Mengembalikan angka yang menunjukkan jenis data suatu nilai'),
  (447, 'UNICHAR', 'Excel 2013+', 'UNICHAR(number)', 'Mengembalikan karakter Unicode yang dirujuk oleh nilai numerik'),
  (448, 'UNICODE', 'Excel 2013+', 'UNICODE(text)', 'Mengembalikan angka (titik kode) yang sesuai dengan karakter pertama teks'),
  (449, 'UNIQUE', 'Excel 2021+', 'UNIQUE(array, [by_col], [exactly_once])', 'Mengembalikan daftar nilai unik dalam daftar atau rentang'),
  (450, 'UPPER', '-', 'UPPER(text)', 'Mengkonversi teks menjadi huruf kapital semua'),
  (451, 'VALUE', '-', 'VALUE(text)', 'Mengkonversi string teks yang mewakili angka menjadi angka'),
  (452, 'VALUETOTEXT', 'Excel 2021+', 'VALUETOTEXT(value, [format])', 'Mengembalikan teks dari nilai apapun'),
  (453, 'VAR', '-', 'VAR(number1, [number2], ...)', 'Fungsi lama: Menghitung varians berdasarkan sampel (diganti VAR.S)'),
  (454, 'VAR.P', 'Excel 2010+', 'VAR.P(number1, [number2], ...)', 'Menghitung varians berdasarkan seluruh populasi'),
  (455, 'VAR.S', 'Excel 2010+', 'VAR.S(number1, [number2], ...)', 'Menghitung varians berdasarkan sampel'),
  (456, 'VARA', '-', 'VARA(value1, [value2], ...)', 'Menghitung varians berdasarkan sampel, termasuk angka, teks, dan nilai logika'),
  (457, 'VARP', '-', 'VARP(number1, [number2], ...)', 'Fungsi lama: Menghitung varians berdasarkan populasi (diganti VAR.P)'),
  (458, 'VARPA', '-', 'VARPA(value1, [value2], ...)', 'Menghitung varians berdasarkan populasi, termasuk angka, teks, dan nilai logika'),
  (459, 'VDB', '-', 'VDB(cost, salvage, life, start_period, end_period, [factor], [no_switch])', 'Mengembalikan penyusutan aset untuk periode yang ditentukan menggunakan metode saldo menurun ganda'),
  (460, 'VLOOKUP', '-', 'VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])', 'Mencari nilai di kolom pertama tabel dan mengembalikan nilai dari kolom yang ditentukan'),
  (461, 'VSTACK', 'Excel 2024+', 'VSTACK(array1, [array2], ...)', 'Menggabungkan array secara vertikal dan berurutan untuk mengembalikan array yang lebih besar'),
  (462, 'WEBSERVICE', 'Excel 2013+', 'WEBSERVICE(url)', 'Mengembalikan data dari layanan web'),
  (463, 'WEEKDAY', '-', 'WEEKDAY(serial_number, [return_type])', 'Mengembalikan hari dalam seminggu sesuai dengan tanggal (1=Minggu, 2=Senin, dll)'),
  (464, 'WEEKNUM', '-', 'WEEKNUM(serial_number, [return_type])', 'Mengembalikan nomor minggu dari tanggal tertentu dalam tahun'),
  (465, 'WEIBULL', '-', 'WEIBULL(x, alpha, beta, cumulative)', 'Fungsi lama: Mengembalikan distribusi Weibull (diganti WEIBULL.DIST)'),
  (466, 'WEIBULL.DIST', 'Excel 2010+', 'WEIBULL.DIST(x, alpha, beta, cumulative)', 'Mengembalikan distribusi Weibull'),
  (467, 'WORKDAY', '-', 'WORKDAY(start_date, days, [holidays])', 'Mengembalikan tanggal sebelum atau sesudah sejumlah hari kerja'),
  (468, 'WORKDAY.INTL', 'Excel 2010+', 'WORKDAY.INTL(start_date, days, [weekend], [holidays])', 'Mengembalikan tanggal sebelum atau sesudah sejumlah hari kerja dengan parameter akhir pekan kustom'),
  (469, 'WRAPCOLS', 'Excel 2024+', 'WRAPCOLS(vector, wrap_count, [pad_with])', 'Membungkus baris atau kolom vektor yang disediakan menjadi array 2D berdasarkan jumlah nilai yang ditentukan'),
  (470, 'WRAPROWS', 'Excel 2024+', 'WRAPROWS(vector, wrap_count, [pad_with])', 'Membungkus baris atau kolom vektor yang disediakan menjadi array 2D berdasarkan jumlah nilai per baris'),
  (471, 'XIRR', '-', 'XIRR(values, dates, [guess])', 'Mengembalikan tingkat pengembalian internal untuk jadwal arus kas yang tidak periodik'),
  (472, 'XLOOKUP', 'Excel 2021+', 'XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])', 'Mencari suatu rentang atau array dan mengembalikan item yang sesuai dengan kecocokan pertama yang ditemukan'),
  (473, 'XMATCH', 'Excel 2021+', 'XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])', 'Mengembalikan posisi relatif suatu item dalam array atau rentang sel'),
  (474, 'XNPV', '-', 'XNPV(rate, values, dates)', 'Mengembalikan nilai sekarang bersih untuk jadwal arus kas yang tidak periodik'),
  (475, 'XOR', 'Excel 2013+', 'XOR(logical1, [logical2], ...)', 'Mengembalikan XOR logika dari semua argumen (TRUE jika jumlah argumen TRUE adalah ganjil)'),
  (476, 'YEAR', '-', 'YEAR(serial_number)', 'Mengembalikan tahun dari suatu tanggal sebagai bilangan bulat'),
  (477, 'YEARFRAC', '-', 'YEARFRAC(start_date, end_date, [basis])', 'Mengembalikan fraksi tahun yang mewakili jumlah hari antara start_date dan end_date'),
  (478, 'YIELD', '-', 'YIELD(settlement, maturity, rate, pr, redemption, frequency, [basis])', 'Mengembalikan imbal hasil sekuritas yang membayar bunga berkala'),
  (479, 'YIELDDISC', '-', 'YIELDDISC(settlement, maturity, pr, redemption, [basis])', 'Mengembalikan imbal hasil tahunan untuk sekuritas berdiskon'),
  (480, 'YIELDMAT', '-', 'YIELDMAT(settlement, maturity, issue, rate, pr, [basis])', 'Mengembalikan imbal hasil tahunan sekuritas yang membayar bunga pada saat jatuh tempo'),
  (481, 'Z.TEST', 'Excel 2010+', 'Z.TEST(array, x, [sigma])', 'Mengembalikan nilai probabilitas satu sisi dari uji z'),
  (482, 'ZTEST', '-', 'ZTEST(array, x, [sigma])', 'Fungsi lama: Mengembalikan nilai probabilitas satu sisi dari uji z (diganti Z.TEST)');

